name: Continuous Integrations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
